### ISSUE TITLE
Port to Fcitx?

### ISSUE THREAD

**Issue by qingxiang-jia** [lennylxx/google-input-tools-macos#3]
很赞！有没有考虑过移植到Fcitx？目前Fcitx虽然有Google云拼音，但是只是第一个候选词，很多时候还是很局限。

**Comment by lennylxx** [comment]
抱歉，目前没有计划。目前还是会集中精力在完善基本功能，让其达到可以日常使用的状态。

**Comment by qingxiang-jia** [comment]
好的，谢谢
